FROM oven/bun:1-debian

WORKDIR /app

COPY apps/api/package.json apps/api/pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install --frozen-lockfile

COPY apps/api src/

EXPOSE 3001

CMD ["bun", "run", "src/index.ts"]